name = "medical-billing-expert-witness"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npx @cloudflare/next-on-pages"

[[pages_build_output_dir]]
name = ".vercel/output/static"